datasets:
   loader:
    workers: 24
    batch_size: 4
   h36m_train:
    subjects: [0,1,2,3,4]
    rgb: True
    nImages: 10000
    nViews: 4
    batch_size: 4 
    img_size: 128
    workers: 12 
    process_batch: True
    root_dir: '/data/levi/workspace/h36m-fetch/video_processed_resized_crop' 
    kp_list: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31]
   h36m_test:
    subjects: [5,6]
    rgb: True
    nImages: 10000
    nViews: 4
    batch_size: 4 
    img_size: 128
    workers: 12 
    process_batch: True
    root_dir: '/data/levi/workspace/h36m-fetch/video_processed_resized_crop' 
    kp_list: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31]
   mpii_train:
    root_dir: '/data/levi/dataset/mpii_128'
    train: True 
    batch_size: 16
    workers: 12 
   mpii_test:
    root_dir: '/data/levi/dataset/mpii_128_eval'
    train: False 
    batch_size: 16
    workers: 12 
    nsamples: 100000


train_params:
  src_train: 'h36m_train'
  src_test: 'h36m_test'
  tgt_train: 'mpii_train'
  tgt_test: 'mpii_test'
  num_epochs: 500
  epoch_milestones: [300, 400]
  lr: 2.0e-4
  batch_size: 32
  heatmap_var: 0.15
  test: False
  loss_weights:
    geometric: 0.0 
    source_regression: 1
  log_params:
    log_freq_iter: 200
    cpk_freq_epoch: 50
    log_imgs: [50, 100, 200, 300]
    eval_frequency: 200
  betas: !!python/tuple [0.5, 0.999]

model_params:
  kp_detector_params:
    temperature: 0.1
    block_expansion: 32
    max_features: 1024
    num_blocks: 5
    scale_factor: 1 
    num_kp: 32 
    num_channels: 3

