datasets:
   loader:
    workers: 24
    batch_size: 4
   mpii_train:
    root_dir: '/data0/levi/dataset/mpii_128'
    train: True 
    batch_size: 16
    workers: 12 
    use_jitter: True
    nsamples: 100000
   mpii_test:
    root_dir: '/data0/levi/dataset/mpii_128_eval'
    train: False 
    batch_size: 16
    workers: 12 
    nsamples: 100000


train_params:
  src_train: 'h36m_train'
  src_test: 'h36m_test'
  tgt_train: 'mpii_train'
  tgt_test: 'mpii_test'
  num_epochs: 40
  epoch_milestones: [300, 400]
  lr: 2.0e-4
  batch_size: 32
  heatmap_var: 0.15
  test: False
  use_rotation: True
  angle_equivariance: False 
  use_jitter: True
  use_gan: False 
  unrolled_steps : 0
  source_loss: 'heatmap'
  loss_weights:
    geometric: 1.0e-9
    source_regression: 1
    generator_gan: 1
    discriminator_gan: 0.5
  log_params:
    log_freq_iter: 200
    cpk_freq_epoch: 50
    log_imgs: [50, 100, 200, 300]
    eval_frequency: 200
  betas: !!python/tuple [0.5, 0.999]

model_params:
  kp_detector_params:
    temperature: 0.1
    block_expansion: 32
    max_features: 1024
    num_blocks: 5
    scale_factor: 1 
    num_kp: 32 
    num_channels: 3
  discriminator_heatmap_params:
    num_channels: 16 
    num_kp: 15 #15
    kp_variance: 0.01
    block_expansion: 32
    num_blocks: 4
    max_features: 512
    spectral_norm: True 
 
